version: '3.8'
services:
  sports-data:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysql:3306/sport?allowPublicKeyRetrieval=true&useSSL=false
    volumes:
      - ./:/app
  #    command: java -jar app.jar -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  mysql:
    image: mysql:8.0.23
    cap_add:
      - ALL
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=sport
      - MYSQL_PASSWORD=sport
      - MYSQL_DATABASE=sport
    volumes:
      - sports-data-mysql:/var/lib/mysql
volumes:
  sports-data-mysql:
    external: true
